#!/usr/bin/env ruby

require 'rexml/document'  
include REXML  

port = ARGV[0]
path = ARGV[1]
placeholder = ARGV[2]
exit 1 unless port && path && placeholder

full_path = File.join(File.dirname(__FILE__), 'app', path)
File.open(full_path,'r') do |file|     
    reg =  Regexp.new('\\$' + placeholder)
    buffer = file.read.gsub(reg, port)
    File.open(full_path, "w") { |fw| fw.write(buffer) }  
end

